Fix bug in variance assumption table when trying to show an error
jasp-stats/jaspTTests pull request #148
Opened 2022-09-19 12:59 UTC by vandenman

Fixes https://github.com/jasp-stats/jasp-test-release/issues/1976

I'd request @juliuspf to review, but I think he can't install developer modules.

New results look like this:

![image](https://user-images.githubusercontent.com/21319932/191022402-578d39ee-8842-44b5-9d64-b6cde00a30d9.png)

See the test issue for the jasp file that produces the error.

I additionally changed `"F"` to `"fStat"` because that is the column is called, https://github.com/jasp-stats/jaspTTests/blob/b49bcd34d13fe0ebbfc48c41ab426dfb2b23b6c1/R/ttestindependentsamples.R#L205

2022-09-19 13:44 UTC, Kucharssim requested changes
I still get this error (with the file from @juliuspf in the issue):

```r
Error in .ttestIndependentEqVarFill(equalityVariance, dataset, options): object 'result' not found

Stack trace
tryCatchOne(expr, names, parentenv, handlers[[1]])

doTryCatch(return(expr), name, parentenv, handler)

withCallingHandlers(expr = analysis(jaspResults = jaspResults, dataset = dataset, options = options), error = .addStackTrace)

analysis(jaspResults = jaspResults, dataset = dataset, options = options)

TTestIndependentSamples(...)

.ttestIndependentEqVarTable(jaspResults, dataset, options, ready, type)

.ttestIndependentEqVarFill(equalityVariance, dataset, options)
```

2022-09-19 13:57 UTC, juliuspf commented
In general, I can install dev modules. Only the regression module did not work. But I won't complain about less work

2022-09-20 07:18 UTC, vandenman commented
@Kucharssim does the error also persist if you rename the module to jaspTTests2? I noticed that for me the old t-test module kept being used so I worked in the jasp-desktop/Modules directly.

2022-09-20 08:09 UTC, Kucharssim commented
> @Kucharssim does the error also persist if you rename the module to jaspTTests2?

I built JASP with your branch checked out and it still persists there as well.

2022-09-20 08:26 UTC, Kucharssim commented
Hang on, I accidentally checked out a wrong branch, sorry 😓 It seems to work then

2022-09-20 08:26 UTC, Kucharssim approved these changes

2022-09-20 08:27 UTC, merged