Bayesian Model Averaged T-Test
jasp-stats/jaspTTests pull request #205
Opened 2023-06-08 07:51 UTC by FBartos

Adds Bayesian Model Averaged T-Test analysis to JASP.

Currently requires:
RoBTT: `FBartos/RoBTT@JASP-updates2`
BayesTools: `FBartos/BayesTools@JASP-RoBTT-fixes`

2023-06-08 13:08 UTC, vandenman requested changes
The code looks mostly fine, although I haven't tested it yet in Jasp. I'm still not sure if we really want Stan and related packages this low in our dependency chain though. Before this PR "only" jaspMetaAnalysis, jaspMixedModels, jaspProphet, and jaspCochrane depend on Stan. After this PR that would also include jaspTTests, jaspAnova, jaspRegression, jaspEquivalenceTTests, and jaspSummaryStatistics. So most of the common modules would then depend on Stan, which is not a good development for our build process.

2023-06-09 07:40 UTC, FBartos commented on R/ttestbayesianmodelaveragedinternal.R
> +      BF                 = BayesTools::format_BF(bf[i], logBF = options[["bayesFactorType"]] == "LogBF10", BF01 = options[["bayesFactorType"]] == "BF01")
It's a critical dependency of RoBTT, I can add it into imports too or rewrite it, depends what you think is better.

2023-06-12 08:12 UTC, FBartos commented on R/ttestbayesianmodelaveragedinternal.R
> +      BF                 = BayesTools::format_BF(bf[i], logBF = options[["bayesFactorType"]] == "LogBF10", BF01 = options[["bayesFactorType"]] == "BF01")
btw, why isn't this function part of jaspBase?

```
.formatBf  <- function(BF, bayesFactorType){
  return(switch(
    bayesFactorType,
    "BF10"    = BF,
    "BF01"    = 1/BF,
    "LogBF10" = log(BF)
  ))
}
```
or I just can't find it?

2023-06-12 08:25 UTC, FBartos commented on inst/qml/common/ModelAveragedTTestPriors.qml
> +			if (componentType == "modelsEffect")
I changed it but I don't find it much simpler as there needs to be explicit break statements, i.e.,\

```
switch (componentType) 
		{
		  case "modelsEffect":				qsTr("Effect"); break;
		  case "modelsEffectNull":			qsTr("Effect (null)"); break;
		  case "modelsHeterogeneity":		qsTr("Heterogeneity (precision allocation)"); break;
		  case "modelsHeterogeneityNull":         qsTr("Heterogeneity (null)"); break;
		  case "modelsOutliers":		                qsTr("Outliers (degrees of freedom + 2)"); break;
		  case "modelsOutliersNull":	                qsTr("Outliers (null)"); break;
		}
```

2023-06-14 16:49 UTC, closed without merging